- README.md
- lib/fastlane/plugin/fueled/actions/create_github_release.rb
- lib/fastlane/plugin/fueled/actions/define_versions_android.rb
- lib/fastlane/plugin/fueled/actions/define_versions_ios.rb
- lib/fastlane/plugin/fueled/actions/set_app_versions_android.rb
- lib/fastlane/plugin/fueled/actions/set_app_versions_plist_ios.rb
- lib/fastlane/plugin/fueled/actions/set_app_versions_xcodeproj_ios.rb
- lib/fastlane/plugin/fueled/actions/tag.rb
* As observed by @robdeans , the build config was duplicated in the tag name. It appears some [other actions](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/blob/ff089f0f97c99d9769a3039c47de11b3aad4549d/lib/fastlane/plugin/versioning/actions/increment_build_number_in_xcodeproj.rb#L29) were messing around with the shared `BUILD_NUMBER` value.
> [Build Number] Use a dedicated shared value for build number

- lib/fastlane/plugin/fueled/actions/define_versions_android.rb
- lib/fastlane/plugin/fueled/actions/generate_changelog.rb
- lib/fastlane/plugin/fueled/actions/set_app_versions_android.rb
* Use correct platform for the `define-versions-android` action.
* Convert build number to string when defining the build number environment variable in `set-versions-android`.
* Use `tac` instead of `tail -r` when the host machine is Linux based as `tail -r` does not work on Linux based machines.
> Fix android specific actions

- README.md
- lib/fastlane/plugin/fueled/actions/move_linear_tickets.rb
* Add an action to move linear tickets from a state to another, allowing filtering by labels. For instance, it can move all the tickets labeled `Frontend` that are `Pending Deploy` to `Pending QA`. Use this with nightly builds, and you have a decent setup to move the tickets to `Pending QA` as builds are delivered. This action is an port of the [existing custom bitrise step](https://github.com/Fueled/bitrise-custom-steps/tree/master/update-linear-tickets).
Here's an [Insomnia workspace](https://github.com/Fueled/fastlane-plugin-fueled/files/7627306/Insomnia_2021-11-30.json.zip) that allows to read label IDs and state IDs for an easy environment variable setup.
> [Linear] Add an action to move linear tickets

- lib/fastlane/plugin/fueled/actions/tag.rb
* Fastlane was always adding a [message to tags](https://github.com/fastlane/fastlane/blob/dac31640214dc976da675e863d0efbd4a99cb526/fastlane/lib/fastlane/actions/add_git_tag.rb#L23) (`-m`) if none was provided, which we do not want. This follows what was previously implemented in the [custom Bitrise step](https://github.com/Fueled/bitrise-custom-steps/blob/c63e803409eb5b3958ce4ef75a99150d4f8888b7/git-tag/step.sh).
> [Git-Tag] Use our own tag action instead of fastlane's

- README.md
- lib/fastlane/plugin/fueled/actions/define_versions_flutter.rb
- lib/fastlane/plugin/fueled/actions/set_app_versions_flutter.rb
- lib/fastlane/plugin/fueled/helper/fueled_helper.rb
* Add `define_versions` and `set_versions` variants for Flutter projects. They read and write the `pubspec.yaml` file
> [Flutter] Add flutter version read and write

- README.md
- lib/fastlane/plugin/fueled/actions/is_build_necessary.rb
* Introduce an action to determine if build is necessary. This will help save some build credits for nightly builds on inactive  projects.
Use it like so : 
```
lane :app_center do
unless is_build_necessary
UI.important "Skipping build"
next
end
pre_build
define_versions_ios
set_app_versions_xcodeproj_ios
build
upload_to_app_center
tag
create_github_release
post_build
end
```
> [Action/Necessary] Introduce an action to determine if build is necessary

- README.md
- lib/fastlane/plugin/fueled/actions/upload_to_app_center.rb
**This PR handles following updates**
- The ability to provide AppCenter owner name as an environment variable so that AppCenter builds can be distributed to client's AppCenter accounts as well. I've added a default value as `Fueled` so that existing apps/workflows continue to work.
**Why was this change needed**
- We recently migrated Fennel's codebase to client's repo and AppCenter account but the App Center upload action failed because the plugin has AppCenter owner name hardcoded as `Fueled`.
> feat(appcenter): add option to specify AppCenter owner as environment variable

- lib/fastlane/plugin/fueled/actions/install_profiles.rb
Only inspect mobileprovision files. This is needed as the `profiles` folder contains a `.gitignore` file so we can actually add the folder to version control even when it's empty (needed for the project template).
> [Profiles] Only inspect mobileprovision files

- lib/fastlane/plugin/fueled/actions/move_linear_tickets.rb
- lib/fastlane/plugin/fueled/helper/fueled_helper.rb
* Consolidate nil and empty checks for linear inputs. Having the values as `VALUE=` in the env file passes an empty value, and not a nil one. This PR adds the empty check in addition to the nil check.
> [Linear] Consolidate nil and empty checks for linear inputs

- README.md
- lib/fastlane/plugin/fueled/actions/ci_checks_flutter.rb
- lib/fastlane/plugin/fueled/actions/formatting_checks_flutter.rb
- lib/fastlane/plugin/fueled/actions/generate_files_flutter.rb
This PR adds a few Flutter actions which were earlier being accomplished using scripts in the Flutter template. It's companion PR can be found [here](https://github.com/Fueled/project-template-flutter/pull/32) which removes the scripts from the Flutter template.
> feat(flutter): add actions to replace flutter scripts

- lib/fastlane/plugin/fueled/actions/generate_files_flutter.rb
The [nightly build for the template](https://github.com/Fueled/project-template-flutter/runs/5555923074?check_suite_focus=true) has been failing since I removed scripts from it. The issue is that in case of PR check, `flutter pub get` is called by the `formatting_checks_flutter` action. However, in case of nightly builds, that action isn't invoked and as such, the dependencies aren't fetched.
This PR fixes the issue by introducing a `flutter pub get` command in the `generate_files_flutter` action.
> fix(*): get dependencies before generating files

- .gitignore
- README.md
- lib/fastlane/plugin/fueled/actions/define_versions_android.rb
- lib/fastlane/plugin/fueled/actions/define_versions_flutter.rb
- lib/fastlane/plugin/fueled/actions/define_versions_ios.rb
- lib/fastlane/plugin/fueled/actions/define_versions_react_native.rb
- lib/fastlane/plugin/fueled/actions/generate_changelog.rb
- lib/fastlane/plugin/fueled/helper/fueled_helper.rb
- Certain projects may need versioning bumps beyond the 1.x.x limit, so made a provision that defaults to version limiting unless we specify the need to skip it via `DISABLE_VERSION_LIMIT` environment variable.
- Additionally current configuration changelog is tied to linear which is handy as a default, however we might need non linear ticketing urls, we can supply them using a `TICKET_BASE_URL` environment variable.
- Added functionality to filter last tag by `BUILD_CONFIGURATION` environment variable. This ensures the versioning doesn't interfere with different build types (snapshot, release).
> Remove version limiting and add configurable ticket URLs

- lib/fastlane/plugin/fueled/helper/fueled_helper.rb
adds additional check to the return value of fetch_last_tag when it is empty string instead of nil
> fix short_version_from_tag

- fastlane-plugin-fueled.gemspec
- This appcenter version is ruby 3 compatible, older one was throwing[ this issue
](https://github.com/microsoft/fastlane-plugin-appcenter/issues/279) and the fix is in the [new version](https://github.com/microsoft/appcenter/issues/2357)
> chore(appcenter): update appcenter to support ruby 3.x

- lib/fastlane/plugin/fueled/actions/ci_checks_flutter.rb
[Sometimes](https://github.com/Fueled/five-resorts-flutter/runs/6775662604?check_suite_focus=true#step:20:539), projects do not have any integration tests and hence, the `ci_checks_flutter` action fails. This PR makes running the integration tests optional.
> feat(*): add the ability to skip integration tests on flutter

- lib/fastlane/plugin/fueled/actions/define_versions_ios.rb
- lib/fastlane/plugin/fueled/helper/fueled_helper.rb
Make sure version is not `nil` before splitting it
Also pull version number regardless of the build configuration
- iOS
> [iOS] Make sure version is not nil before splitting it

- lib/fastlane/plugin/fueled/helper/fueled_helper.rb
Pull short version per build type
This is needed as in some circumstances, the *Marketing Version* (or Short Version) will be different per build configuration.
> [iOS][ShortVersion] Pull short version per build type

- lib/fastlane/plugin/fueled/actions/generate_files_flutter.rb
Not all projects have localization set up so this PR makes the generation of localization files optional.
> fix(*): skip generation of localization files

- README.md
- lib/fastlane/plugin/fueled/actions/generate_secrets_ios.rb
**This PR includes following updates**
- Adds a new action that lets you generate the ArkanaKeys package that is part of Fueled iOS Template to manage project keys and secrets.
> feat(secrets): add action to generate ArkanaKeys package

- README.md
- lib/fastlane/plugin/fueled/actions/check_code_coverage_ios.rb
- lib/fastlane/plugin/fueled/version.rb
This pull request adds an action that handles the check of the code coverage . Usually, this action should be right after the `pr_check` one, where we need to guarantee that our PR changes support the minimum code coverage percentage (passed to this action) before merging it.
I created a JSON config file for helping us in the code coverage calculation, the below config file will check in the provided `targets` for files that contain `ViewModel` in their names.
```json
{
"targets": [
"FueledTemplate",
"FueledTemplateAPIKit",
"FueledTemplateHelpers"
],
"file_name_exclude": [],
"file_name_include": [
"ViewModel"
]
}
```
In order to generate the result bundle file which has the `xcresult` extension, we will need to set the `result_bundle` and the `code_coverage` both to true. This will …
> Add check code coverage action for iOS

- lib/fastlane/plugin/fueled/actions/set_app_versions_flutter.rb
`1.0.0+19-Release` - this is how the version is being set currently. However, if you look at the image above, you can see that the part after `+` is supposed to be the build number. This results in the builds not having the release / snapshot suffix.
[Android Builds](https://appcenter.ms/orgs/Fueled/apps/Alpas-1/distribute/releases)
[iOS Builds](https://appcenter.ms/orgs/Fueled/apps/Alpas/distribute/releases)
[Flutter Builds](https://appcenter.ms/orgs/Fueled/apps/Meow-Wolf-Android/distribute/releases)
This PR aims to fix that by adding the build type parameter to the version name instead of version code
> fix(*): fix flutter versioning

- README.md
- lib/fastlane/plugin/fueled/actions/use_git_credential_store.rb
If you need to perform Git commands such as pushing a tag or creating a release on GitHub, you'll require write access to the repository. When using GitHub Actions, you can use the `GITHUB_TOKEN` for authorization.
However, with an external CI/CD provider like Codemagic, you may need to specify the token and username with each Git command or store the credentials using Git Credential Store. The new action simplifies this process.
> Add git credential store action

- lib/fastlane/plugin/fueled/actions/create_github_release.rb
- lib/fastlane/plugin/fueled/helper/fueled_helper.rb
Adds support for multiplatform projects where both iOS and Android assets are produced, by trying to upload all produced assets.
> Upload all available assets when creating GitHub release

- lib/fastlane/plugin/fueled/actions/formatting_checks_flutter.rb
1. As per the latest flutter version below command is failing.
`flutter format -o none --set-exit-if-changed .`
The updated command will be
`dart format -o none --set-exit-if-changed .`
> chore(flutter): update local test command

- lib/fastlane/plugin/fueled/actions/formatting_checks_flutter.rb
There was a formatting issue with the last [merged PR](https://github.com/Fueled/fastlane-plugin-fueled/pull/46) where the extra backslash was being removed, can we quickly review and merge this one? Apologies for the back-and-fro!
> fix(*): fix formatting command

- README.md
- lib/fastlane/plugin/fueled/actions/generate_code_coverage_reports_ios.rb
- lib/fastlane/plugin/fueled/helper/fueled_helper.rb
Each project can have a different place to store these generated reports, we can push them to the repo using the default branch, but some projects don't allow direct push to the default branch, and instead, we should open PRs.
Also, some projects may need to store these reports outside the source code.
So it depends. This action will generate an HTML file for the code coverage and returns the generated file path.
UI updates:
> Generate code coverage reports action (iOS)

- README.md
- lib/fastlane/plugin/fueled/actions/upload_to_test_fairy_android.rb
- lib/fastlane/plugin/fueled/actions/upload_to_test_fairy_ios.rb
- Add support for TestFairy (distribution platform)
- Update readme accordingly
Attached is proof of functionality:
> feat(testfairy): add testfairy support to fastlane

- lib/fastlane/plugin/fueled/actions/define_versions_ios.rb
When fetching the build number on iOS, we are neglecting to pass the `build_type` param which if provided will filter the tags based on environment.
Currently: with no filter provided, the most recent build number is fetched and incremented regardless of the environment. 
```
**Start**
Production/Snapshot-100
...
Snapshot-101
Snapshot-102
Production-103
Snapshot-104
Production-105
```
Expected behavior: build numbers should increment based on their respective environments
```
**Start**
Production/Snapshot-100
...
Snapshot-101
Snapshot-102
Production-101
Snapshot-103
Production-102
```
> fix(ios-build-number): filter build number tag by build_type

- fastlane-plugin-fueled.gemspec
- lib/fastlane/plugin/fueled/actions/unit_tests_flutter.rb
Flutter tests can run more efficiently if we leverage [the concurrency parameter](https://pub.dev/packages/test#test-concurrency). This is by default set to half of whatever cores there are on the machine. 
This PR updates it to use all cores in an attempt to run as many tests as possible in parallel.
I've seen improvements of over 38% in the test command when I ran it for meow wolf
With concurrency parameter : 42s 
Without concurrency parameter : 58s
> chore(flutter): use concurrency to improve flutter tests

- lib/fastlane/plugin/fueled/actions/unit_tests_flutter.rb
Github reporter is more concise than the default reporter
Old Reporter
Github Reporter
> chore(reports): ensure we use github as the default reporter

- lib/fastlane/plugin/fueled/actions/generate_files_flutter.rb
- lib/fastlane/plugin/fueled/version.rb
The current setup did not allow generating code for multiple modules/packages in flutter. This PR allows a comma-separated string to be specified that would represent paths of all the packages that need build runner to be run in them.
New behaviour:
If one wishes to run the generator in multiple modules i.e.  lets say current directory and "feature-auth" module then they could supply this `.,feature-auth` as the parameter in order for build runner to run in both directories.
> feat(flutter): support multi-module codegen
